baseURL: "/"
title: "Isabella Dillen"
languageCode: "nl-be"
paginate: 10

# Gebruik Hugo Modules i.p.v. lokale theme-map
module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

# Vertel Hugo welk theme te gebruiken
theme: "hugo-PaperMod"

menus:
  main:
    - name: "Sport"
      url: "/sport/"
      weight: 10
    - name: "Tech"
      url: "/tech/"
      weight: 20
    - name: "School"
      url: "/school/"
      weight: 30
    - name: "Blog"
      url: "/post/"
      weight: 40
    - name: "Over mij"
      url: "/about/"
      weight: 50
